# **üß© DataFrame Merging, Joining, and Concatenation**

---

## üîÅ `pd.merge()` ‚Äì Merging DataFrames

- ‚ûï Used to combine two DataFrames based on a common column (like SQL JOINs).

```python
    import pandas as pd

    df1 = pd.DataFrame({
        'ID': [1, 2, 3],
        'Name': ['Alice', 'Bob', 'Charlie']
    })

    df2 = pd.DataFrame({
        'ID': [1, 2, 4],
        'Score': [85, 90, 95]
    })
```

### üîπ Inner Merge (default)
- ‚úÖ Only rows with matching IDs in both DataFrames are included.
```python
    pd.merge(df1, df2, on='ID', how='inner')
```


### üî∏ Outer Merge
- üßæ All rows from both DataFrames included, NaN where data is missing.
```python
    pd.merge(df1, df2, on='ID', how='outer')
```


### üîπ Left Merge
- ‚¨Ö All rows from `df1` (left), matching from `df2`, NaN where not matched.
```python
    pd.merge(df1, df2, on='ID', how='left')
```


### üî∏ Right Merge
- ‚û° All rows from `df2` (right), matching from `df1`, NaN where not matched.
```python
    pd.merge(df1, df2, on='ID', how='right')
```

---

## üîó `df.join()` ‚Äì Joining by Index
- üîÑ Joins columns from another DataFrame using index.
- üß≠ Default is left join. Use `how='inner'`, `outer`, `right`, etc., as needed.
```python
    df1 = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
    df2 = pd.DataFrame({'Score': [85, 90, 95]}, index=[1, 2, 4])

    df1.join(df2, how='left')
```

---

## üìö `pd.concat()` ‚Äì Concatenation

- üìè Used to **stack** DataFrames vertically (`axis=0`) or horizontally (`axis=1`).

```python
    df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
    df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})
```

### ‚¨á Vertical Concatenation (axis=0)
- üìâ Adds rows. Index will repeat unless you reset it.
```python
    pd.concat([df1, df2], axis=0)
```


### ‚û° Horizontal Concatenation (axis=1)
- üß± Adds columns side by side. Make sure the number of rows align.
```python
    pd.concat([df1, df2], axis=1)
```

---

## ‚úÖ Summary Points
- üîç Use `merge()` for relational joins based on column values.
- üîó Use `join()` for index-based joining.
- üß± Use `concat()` to stack DataFrames either vertically or horizontally.
- üéØ Choose `how='inner'`, `'outer'`, `'left'`, or `'right'` depending on inclusion logic.

---

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'ID':[1,2,3,4],
                    'Name':['Alice','Bob','Charlie','David']
        })
df2 = pd.DataFrame({'ID':[1,3,4,5],
                    'Age':[22,23,24,25]
        })
merged_df = pd.merge(df1, df2, on='ID', how='left') # default: inner
print(merged_df)

In [ ]:
df1 = pd.DataFrame({'value1':[1,2,3]},index=['A','B','C'])
df2 = pd.DataFrame({'value2':[4,5,6]},index=['B','C','D'])
joined_df = df1.join(df2, how='right') # default:left
print(joined_df)

In [ ]:
df1 = pd.DataFrame({'A':[1,2], 'B':[3,4]})
df2 = pd.DataFrame({'C':[5,6], 'D':[7,8]})
res = pd.concat([df1, df2], axis=0) # default:axis=0
print(res)

# **TASK 1:**
**Problem Statement:**
* Billa needs a program to manage food inventory details. The program will take the names of various food items, along with their prices and quantities.
* Using this input, the program should create a data frame containing columns for food name, price, quantity, and total price.
* The total price for each food item will be calculated by multiplying its price by its quantity. Finally, the program will display the data frame with the calculated total prices.

---

**Input Format:**
* The input consists of 3 lines, each line containing three space-separated values representing the details of the:
    - Food name (string)
    - Price of the food item (floating-point number)
    - Quantity of the food item (integer)

---

**Output Format:**
* The output should be a data frame displaying the details of each food item and its total price, rounded to two decimal points, with the following columns:
    - Food Name
    - Price
    - Quantity
    - Total Price
* The rows should correspond to the order of the input.

---

**Code Constraints:**
* The input should consist of exactly three food items.
    - 1.0 ‚â§ price ‚â§ 1000.0
    - 1 ‚â§ quantity ‚â§ 25

---

**Sample test case:**
* **Input:**
    - Chicken 800.5 4
    - Rice 100.75 7
    - Beans 123.25 8

* **Output:**

    |   | Food Name |  Price | Quantity | Total Price |
    |---|-----------|--------|----------|-------------|
    | 0 |   Chicken | 800.50 |        4 |     3202.00 |
    | 1 |      Rice | 100.75 |        7 |      705.25 |
    | 2 |     Beans | 123.25 |        8 |      986.00 |

In [ ]:
import pandas as pd

def inventory():
    details = []
    for i in range(3):
        name, price, quantity = input().strip().split()
        details.append({
            'Food Name': name,
            'Price': float(price),
            'Quantity': int(quantity)
        })
    return details

df = pd.DataFrame(inventory())
df['Total Price'] = (df['Price'] * df['Quantity']).round(2)
print(df)